rmdn/rmadan/urls.py
from django.urls import path

from .views import index, UserPage

app_name = 'rmadan'
urlpatterns = [
    path('/', index, name='index'),
    path('<name>/', UserPage, name='UserPage')

]

rmdn/rmdn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rmadan.urls'))

]

rmdn/rmadan/models.py
from django.db import models

# Create your models here.

rmdn/rmadan/views.py
from django.shortcuts import render, redirect


# Create your views here.
def UserPage(request, name):
    contect = {'name': name}
    return render(request, 'name.html', contect)


def index(request):
    if request.method == 'POST':
        name = request.POST['name']
        url = '/'+name
        return redirect(url)
    else:
        return render(request, 'index.html')

rmdn/rmadan/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
       <form class="form-horizontal" role="form" action="{% url 'rmadan:index'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                name:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="name" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
       </form>

</body>
</html>

rmdn/rmadan/templates/name.html
{% load staticfiles %}

<html dir="rtl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/new3.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Changa|Lalezar" rel="stylesheet">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1930989189604947",
    enable_page_level_ads: true
  });
</script>
</head>
<body style="background-image: url(40007-happiestbday.jpg)">
	<marquee class="m1" behavior="scroll" direction="up" scrolldelay="5"> <br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
	</marquee>
	<marquee class="m2" behavior="scroll" direction="up" scrolldelay="5"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
		<img src="./files/127.png" height="65px" width="34px"><br>
		<img src="./files/125.png" height="65px" width="18px"><br>
		<img src="./files/126.png" height="65px" width="34px"><br>
	</marquee>
	<center>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<script>
		  (adsbygoogle = window.adsbygoogle || []).push({
			google_ad_client: "ca-pub-1930989189604947",
			enable_page_level_ads: true
		  });
		</script>
	</center>
	<div class="container">
		<div class="main-greeting">
			<div align="center html2canvas-ignore">
				<div style="font-size:24px; font-weight: 800; color: white; font-family: tahoma; text-shadow:2px 2px rebeccapurple, 2px 2px rebeccapurple;">
					<p id="demo" style="color:white;font-size:14px;text-shadow:1px 1px rebeccapurple, 1px 1px rebeccapurple;"></p>
					<div class="main_body">
						<figure>
						<!-- but name heare !-->
							<h1 class="naming">{{name}}</h1>
							<h1 class="naming">{{name}}</h1>
							<h1 class="naming">{{name}}</h1>
							<h1 class="naming">{{name}}</h1>
							<h1 class="naming">{{name}} </h1>
						</figure>
						<div class="vi" style="text-align: center;">
							<img src="./files/Snow_falling1.gif" class="swing1" alt="diwali" style="width: 100%; height:100px;">
							<h3>أتمنى لك</h3>
							<h2>رمضان كريم</h2> <p id="demo"></p>
							<img class="center swing" src="./files/heart.png" width="40px" height="80px" alt="Happy New Year greating wishes">
							<img class="center swing1" src="./files/heart2.png" width="80px" height="80px" alt="Happy New Year greating wishes">
							<img class="center swing2" src="./files/heart3.png" width="40px" height="80px" alt="Happy New Year greating wishes">
							<img class="center swing3" src="./files/heart4.png" width="40px" height="80px" alt="Happy New Year greating wishes">
							<br>
							<br>
							<h2> <img src="./files/20183.png" class="img-responsive" alt="NEW YEAR" style="width: 250px; height:150px;">
							</h2>

							<script>
// Set the date we're counting down to
var countDownDate = new Date("May 16, 2018 00:00:00").getTime();

// Update the count down every 01 second
var x = setInterval(function() {a

  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now an the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML ="<i>الأيام </i> " + days + " <i>، الساعات </i> " + hours + "<i>، الدقائق </i> "
  + minutes + "<i>، الثواني </i> " + seconds  ;

  // If the count down is finished, write some text
  if (distance < 0) {
  	clearInterval(x);
  	document.getElementById("demo").innerHTML = "💕 رمضان مبارك 💕";
  }
}, 1000);
</script>
</div>
</div>
<p aling="center" style="font-size: 15px;color:white;"><b></b></p><b>إذا دخل رمضان،<br>
فتحت أبواب الجنة،<br>
و غلقت أبواب جهنم،<br>
و سلسلت الشياطين.<br>
اللهم بلغنا رمضان،<br>
و أنت راض عنا،<br><p></p></b><p></p> <img src="./files/15.png" height="40px" width="40px">
<div class="busi">[your name]<br><img src="./files/4.png" height="35px" width="35px">
	<center>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1930989189604947",
    enable_page_level_ads: true
  });
</script>
	</center>
</div>
</div>
</div>
</div>
<center>


	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118258222-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-118258222-1');
	</script>
</center>
	</div>
</body>
</html>